### ISSUE TITLE
relicense MIT for project 

### ISSUE THREAD

**Issue by Jemerald83** [CommunityToolkit/ColorCode-Universal#32] opened 2022-11-16 16:21 UTC
I have reapplied mit license im not sure who to report to because some how lost communication with ocm supervisor

**Comment by michael-hawker** [comment] 2023-06-19 18:02
@Jemerald83 not sure what you're asking here?

Duplicate of #20? Done in #25...

**Closed as completed by michael-hawker** 2023-06-19 18:02 UTC
